name: Manual Cherry-Pick

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: "Commit SHA to cherry-pick"
        required: true
      target_branch:
        description: "Target branch to cherry-pick into"
        required: true
        default: "release/1.0"

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick commit
        run: |
          COMMIT_SHA="${{ github.event.inputs.commit_id }}"
          TARGET_BRANCH="${{ github.event.inputs.target_branch }}"

          echo "🔹 Cherry-picking commit $COMMIT_SHA into $TARGET_BRANCH"

          git fetch origin $TARGET_BRANCH
          git checkout $TARGET_BRANCH

          if git cherry-pick $COMMIT_SHA; then
            echo "✅ Cherry-pick successful, pushing..."
            git push origin $TARGET_BRANCH
          else
            echo "⚠️ Conflict occurred, creating PR branch..."
            git cherry-pick --abort
            NEW_BRANCH="cherry-pick-${COMMIT_SHA:0:7}"

            git checkout -b $NEW_BRANCH
            git cherry-pick $COMMIT_SHA || true
            git push origin $NEW_BRANCH

            # 🔹 Check if branch actually has changes
            if [ "$(git rev-parse $TARGET_BRANCH)" = "$(git rev-parse HEAD)" ]; then
              echo "⚠️ No changes to cherry-pick. Skipping PR."
              exit 0
            fi

            echo "📌 Creating Pull Request..."
            gh pr create \
              --base $TARGET_BRANCH \
              --head $NEW_BRANCH \
              --title "Cherry-pick $COMMIT_SHA into $TARGET_BRANCH" \
              --body "Auto cherry-pick of commit $COMMIT_SHA into $TARGET_BRANCH"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
