name: Cherry-pick Commit

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to cherry-pick"
        required: true
      target_branch:
        description: "Target branch to cherry-pick into"
        required: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Perform cherry-pick
        env:
          COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        run: |
          set -e

          echo "🔹 Cherry-picking commit $COMMIT_SHA into $TARGET_BRANCH"

          git fetch origin $TARGET_BRANCH
          git checkout -b $TARGET_BRANCH origin/$TARGET_BRANCH

          BRANCH_NAME="cherry-pick-$COMMIT_SHA"

          # Try cherry-pick
          if ! git cherry-pick $COMMIT_SHA; then
            echo "⚠️ Conflict occurred, creating PR branch..."
            
            git checkout -b $BRANCH_NAME

            # Stage everything (conflict markers will remain in files)
            git add .

            # Commit the conflict state so PR can be opened
            git commit -m "Cherry-pick $COMMIT_SHA into $TARGET_BRANCH (with conflicts to resolve)"

            git push origin $BRANCH_NAME

            gh pr create \
              --base $TARGET_BRANCH \
              --head $BRANCH_NAME \
              --title "Cherry-pick $COMMIT_SHA into $TARGET_BRANCH" \
              --body "This PR was created automatically and contains conflicts. Please resolve them manually."

            exit 0
          fi

          echo "✅ Cherry-pick succeeded, creating PR branch..."
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

          gh pr create \
            --base $TARGET_BRANCH \
            --head $BRANCH_NAME \
            --title "Cherry-pick $COMMIT_SHA into $TARGET_BRANCH" \
            --body "Cherry-picked successfully without conflicts."
