name: Auto Cherry-Pick

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to cherry-pick'
        required: true
      target_branch:
        description: 'Target branch for cherry-pick'
        required: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout target branch
        run: git checkout ${{ github.event.inputs.target_branch }}

      - name: Try Cherry-pick
        id: cherry-pick
        run: |
          set +e
          git cherry-pick ${{ github.event.inputs.commit_id }}
          status=$?
          set -e
          echo "status=$status" >> $GITHUB_OUTPUT

      - name: Push if no conflict
        if: steps.cherry-pick.outputs.status == '0'
        run: |
          git push origin HEAD:${{ github.event.inputs.target_branch }}
          echo "✅ Cherry-pick applied and pushed directly to ${{ github.event.inputs.target_branch }}"

      - name: Handle conflicts by creating PR
        if: steps.cherry-pick.outputs.status != '0'
        run: |
          echo "❌ Conflict occurred! Creating PR..."
          BRANCH_NAME="cherry-pick-${{ github.event.inputs.commit_id }}-to-${{ github.event.inputs.target_branch }}"
          
          # Abort cherry-pick and create branch with conflicts
          git cherry-pick --abort || true
          git checkout -b $BRANCH_NAME
          git cherry-pick ${{ github.event.inputs.commit_id }} || true
          git push origin $BRANCH_NAME

          gh pr create \
            --base ${{ github.event.inputs.target_branch }} \
            --head $BRANCH_NAME \
            --title "Cherry-pick ${{ github.event.inputs.commit_id }} to ${{ github.event.inputs.target_branch }}" \
            --body "This PR was automatically created because cherry-picking commit ${{ github.event.inputs.commit_id }} into ${{ github.event.inputs.target_branch }} resulted in conflicts. Please resolve them manually."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
