name: Manual Cherry-Pick

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to cherry-pick"
        required: true
      target_branch:
        description: "Branch to cherry-pick onto"
        required: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # full history for cherry-pick

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Perform cherry-pick directly on target branch
        env:
          COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        run: |
          set -e
          echo "🔹 Cherry-picking commit $COMMIT_SHA into $TARGET_BRANCH"

          # Checkout target branch
          git fetch origin $TARGET_BRANCH
          git checkout $TARGET_BRANCH

          # Try cherry-pick
          if ! git cherry-pick $COMMIT_SHA; then
            echo "❌ Conflict occurred! Cherry-pick could not be applied."
            echo "Please resolve manually on branch $TARGET_BRANCH."
            exit 1
          fi

          echo "✅ Cherry-pick succeeded, pushing directly to $TARGET_BRANCH..."
          git push origin $TARGET_BRANCH
